## Business Usecase: Develop a model that provides product associations for store transactional data.

## Association RUle Mining technique

In [2]:
pip install apyori

Requirement already satisfied: apyori in e:\Sindhura\Machine Learning 1535\repository\venv\Lib\site-packages (1.1.2)
Note: you may need to restart the kernel to use updated packages.

## Restart the kernel and run all the cells

In [3]:
## Load the data
import pandas as pd
path = r"https://raw.githubusercontent.com/sindhura-nk/Datasets/refs/heads/main/store_data.csv"
df = pd.read_csv(path,header=None)
df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
1,burgers,meatballs,eggs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,chutney,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,turkey,avocado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,mineral water,milk,energy bar,whole wheat rice,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Generate a nested list where each sub list contains complete row information

    example : [[shrimp,burgers
    chutney
    turkey
    mineral water
    low fat yogurt
    whole wheat pasta
    soup
    frozen vegetables
    french fries
    eggs
    cookies
    turkey
    spaghetti
    mineral water
    mineral water
    shrimp
    turkey
    turkey
    meatballs],
    [meatballs,eggs],
    [pasta]]

In [4]:
df.shape

(7501, 20)

In [5]:
rows = df.shape[0]
cols = df.shape[1]

In [6]:
print(rows,cols)

7501 20

In [7]:
# i=0
# 1st row's data being added list

In [8]:
for j in range(df.shape[1]):
    print(df.values[4,j])

mineral water
milk
energy bar
whole wheat rice
green tea
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan

In [ ]:
records = []
for i in range(rows):
  records.append([str(df.values[i,j]) for j in range(cols)])
records[:10]

**To build the association rules, we need to build the criteria**\

    support : based on data
    confidence : 0.2
    lift : 3

    support : transactions - weekly data: 7days , 5
    support : 7*5/total transactions  = 35/7500

In [ ]:
from apyori import apriori
sup = 7*5/len(df)
conf = 0.2
lift = 3

association_rules = apriori(records,min_support=sup,min_confidence=conf,min_lift=lift)
association_rules = list(association_rules)
association_rules[:10]

[RelationRecord(items=frozenset({'escalope', 'mushroom cream sauce'}), support=0.005732568990801226, ordered_statistics=[OrderedStatistic(items_base=frozenset({'mushroom cream sauce'}), items_add=frozenset({'escalope'}), confidence=0.3006993006993007, lift=3.790832696715049)]),
 RelationRecord(items=frozenset({'pasta', 'escalope'}), support=0.005865884548726837, ordered_statistics=[OrderedStatistic(items_base=frozenset({'pasta'}), items_add=frozenset({'escalope'}), confidence=0.3728813559322034, lift=4.700811850163794)]),
 RelationRecord(items=frozenset({'ground beef', 'herb & pepper'}), support=0.015997866951073192, ordered_statistics=[OrderedStatistic(items_base=frozenset({'herb & pepper'}), items_add=frozenset({'ground beef'}), confidence=0.3234501347708895, lift=3.2919938411349285)]),
 RelationRecord(items=frozenset({'tomato sauce', 'ground beef'}), support=0.005332622317024397, ordered_statistics=[OrderedStatistic(items_base=frozenset({'tomato sauce'}), items_add=frozenset({'ground beef'}), confidence=0.3773584905660377, lift=3.840659481324083)]),
 RelationRecord(items=frozenset({'whole wheat pasta', 'olive oil'}), support=0.007998933475536596, ordered_statistics=[OrderedStatistic(items_base=frozenset({'whole wheat pasta'}), items_add=frozenset({'olive oil'}), confidence=0.2714932126696833, lift=4.122410097642296)]),
 RelationRecord(items=frozenset({'shrimp', 'pasta'}), support=0.005065991201173177, ordered_statistics=[OrderedStatistic(items_base=frozenset({'pasta'}), items_add=frozenset({'shrimp'}), confidence=0.3220338983050847, lift=4.506672147735896)]),
 RelationRecord(items=frozenset({'shrimp', 'frozen vegetables', 'chocolate'}), support=0.005332622317024397, ordered_statistics=[OrderedStatistic(items_base=frozenset({'frozen vegetables', 'chocolate'}), items_add=frozenset({'shrimp'}), confidence=0.23255813953488375, lift=3.2545123221103784), OrderedStatistic(items_base=frozenset({'shrimp', 'chocolate'}), items_add=frozenset({'frozen vegetables'}), confidence=0.29629629629629634, lift=3.1084175084175087)]),
 RelationRecord(items=frozenset({'ground beef', 'spaghetti', 'cooking oil'}), support=0.004799360085321957, ordered_statistics=[OrderedStatistic(items_base=frozenset({'ground beef', 'cooking oil'}), items_add=frozenset({'spaghetti'}), confidence=0.5714285714285714, lift=3.2819951870487856), OrderedStatistic(items_base=frozenset({'spaghetti', 'cooking oil'}), items_add=frozenset({'ground beef'}), confidence=0.3025210084033613, lift=3.0789824749438446)]),
 RelationRecord(items=frozenset({'nan', 'escalope', 'mushroom cream sauce'}), support=0.005732568990801226, ordered_statistics=[OrderedStatistic(items_base=frozenset({'mushroom cream sauce'}), items_add=frozenset({'nan', 'escalope'}), confidence=0.3006993006993007, lift=3.790832696715049), OrderedStatistic(items_base=frozenset({'nan', 'mushroom cream sauce'}), items_add=frozenset({'escalope'}), confidence=0.3006993006993007, lift=3.790832696715049)]),
 RelationRecord(items=frozenset({'nan', 'escalope', 'pasta'}), support=0.005865884548726837, ordered_statistics=[OrderedStatistic(items_base=frozenset({'pasta'}), items_add=frozenset({'nan', 'escalope'}), confidence=0.3728813559322034, lift=4.700811850163794), OrderedStatistic(items_base=frozenset({'nan', 'pasta'}), items_add=frozenset({'escalope'}), confidence=0.3728813559322034, lift=4.700811850163794)])]

In [ ]:
association_rules[0]

RelationRecord(items=frozenset({'escalope', 'mushroom cream sauce'}), support=0.005732568990801226, ordered_statistics=[OrderedStatistic(items_base=frozenset({'mushroom cream sauce'}), items_add=frozenset({'escalope'}), confidence=0.3006993006993007, lift=3.790832696715049)])

In [ ]:
association_rules[0][0]

frozenset({'escalope', 'mushroom cream sauce'})

In [ ]:
association_rules[0][1]

0.005732568990801226

In [ ]:
association_rules[0][2]

[OrderedStatistic(items_base=frozenset({'mushroom cream sauce'}), items_add=frozenset({'escalope'}), confidence=0.3006993006993007, lift=3.790832696715049)]

In [ ]:
association_rules[0][2][0]

OrderedStatistic(items_base=frozenset({'mushroom cream sauce'}), items_add=frozenset({'escalope'}), confidence=0.3006993006993007, lift=3.790832696715049)

In [ ]:
association_rules[0][2][0][2]

0.3006993006993007

In [ ]:
association_rules[0][2][0][3]

3.790832696715049

In [ ]:
results = []
for items in association_rules:
    #Extract product associations
    item_pair = items[0] #frozen set of items
    item_data = [i for i in item_pair] #save the items in a list

    support1 = items[1] # support 

    confidence1 = items[2][0][2]
    lift1 = items[2][0][3]

    results.append([item_data,round(support1,3),round(confidence1,3),round(lift1,2)])
print(results)

[[['escalope', 'mushroom cream sauce'], 0.006, 0.301, 3.79], [['pasta', 'escalope'], 0.006, 0.373, 4.7], [['ground beef', 'herb & pepper'], 0.016, 0.323, 3.29], [['tomato sauce', 'ground beef'], 0.005, 0.377, 3.84], [['whole wheat pasta', 'olive oil'], 0.008, 0.271, 4.12], [['shrimp', 'pasta'], 0.005, 0.322, 4.51], [['shrimp', 'frozen vegetables', 'chocolate'], 0.005, 0.233, 3.25], [['ground beef', 'spaghetti', 'cooking oil'], 0.005, 0.571, 3.28], [['nan', 'escalope', 'mushroom cream sauce'], 0.006, 0.301, 3.79], [['nan', 'escalope', 'pasta'], 0.006, 0.373, 4.7], [['frozen vegetables', 'spaghetti', 'ground beef'], 0.009, 0.311, 3.17], [['milk', 'frozen vegetables', 'olive oil'], 0.005, 0.203, 3.09], [['shrimp', 'frozen vegetables', 'mineral water'], 0.007, 0.305, 3.2], [['frozen vegetables', 'spaghetti', 'olive oil'], 0.006, 0.206, 3.12], [['shrimp', 'frozen vegetables', 'spaghetti'], 0.006, 0.215, 3.01], [['frozen vegetables', 'spaghetti', 'tomatoes'], 0.007, 0.239, 3.5], [['ground beef', 'spaghetti', 'grated cheese'], 0.005, 0.323, 3.28], [['ground beef', 'herb & pepper', 'mineral water'], 0.007, 0.391, 3.98], [['nan', 'ground beef', 'herb & pepper'], 0.016, 0.323, 3.29], [['ground beef', 'spaghetti', 'herb & pepper'], 0.006, 0.393, 4.0], [['milk', 'ground beef', 'olive oil'], 0.005, 0.224, 3.4], [['tomato sauce', 'nan', 'ground beef'], 0.005, 0.377, 3.84], [['shrimp', 'ground beef', 'spaghetti'], 0.006, 0.523, 3.01], [['milk', 'spaghetti', 'olive oil'], 0.007, 0.203, 3.08], [['soup', 'olive oil', 'mineral water'], 0.005, 0.225, 3.42], [['nan', 'whole wheat pasta', 'olive oil'], 0.008, 0.271, 4.13], [['shrimp', 'nan', 'pasta'], 0.005, 0.322, 4.52], [['pancakes', 'spaghetti', 'olive oil'], 0.005, 0.201, 3.05], [['shrimp', 'nan', 'frozen vegetables', 'chocolate'], 0.005, 0.233, 3.26], [['nan', 'ground beef', 'spaghetti', 'cooking oil'], 0.005, 0.571, 3.28], [['nan', 'frozen vegetables', 'spaghetti', 'ground beef'], 0.009, 0.311, 3.17], [['milk', 'frozen vegetables', 'olive oil', 'nan'], 0.005, 0.203, 3.09], [['shrimp', 'nan', 'frozen vegetables', 'mineral water'], 0.007, 0.305, 3.2], [['nan', 'frozen vegetables', 'spaghetti', 'olive oil'], 0.006, 0.206, 3.13], [['shrimp', 'nan', 'frozen vegetables', 'spaghetti'], 0.006, 0.215, 3.02], [['nan', 'frozen vegetables', 'spaghetti', 'tomatoes'], 0.007, 0.239, 3.5], [['nan', 'ground beef', 'spaghetti', 'grated cheese'], 0.005, 0.323, 3.28], [['nan', 'ground beef', 'herb & pepper', 'mineral water'], 0.007, 0.391, 3.98], [['nan', 'ground beef', 'spaghetti', 'herb & pepper'], 0.006, 0.393, 4.0], [['milk', 'ground beef', 'olive oil', 'nan'], 0.005, 0.224, 3.41], [['shrimp', 'nan', 'ground beef', 'spaghetti'], 0.006, 0.523, 3.01], [['milk', 'spaghetti', 'olive oil', 'nan'], 0.007, 0.203, 3.09], [['soup', 'nan', 'olive oil', 'mineral water'], 0.005, 0.225, 3.43], [['pancakes', 'nan', 'spaghetti', 'olive oil'], 0.005, 0.201, 3.06]]

## Save these results inside a dataframe and share with the client

In [ ]:
df_results = pd.DataFrame(results)
df_results.head()

                                  0      1      2     3
0  [escalope, mushroom cream sauce]  0.006  0.301  3.79
1                 [pasta, escalope]  0.006  0.373  4.70
2      [ground beef, herb & pepper]  0.016  0.323  3.29
3       [tomato sauce, ground beef]  0.005  0.377  3.84
4    [whole wheat pasta, olive oil]  0.008  0.271  4.12

In [ ]:
df_results.columns = ["Product_Associations","Support","Confidence","Lift"]
df_results.head()

               Product_Associations  Support  Confidence  Lift
0  [escalope, mushroom cream sauce]    0.006       0.301  3.79
1                 [pasta, escalope]    0.006       0.373  4.70
2      [ground beef, herb & pepper]    0.016       0.323  3.29
3       [tomato sauce, ground beef]    0.005       0.377  3.84
4    [whole wheat pasta, olive oil]    0.008       0.271  4.12

In [ ]:
df_results.to_csv("Product_Associations.csv",index=False)

You can also save the product results separately

In [ ]:
results_1 = []
for items in association_rules:
    #Extract product associations
    item_pair = items[0] #frozen set of items
    item_data = [i for i in item_pair] #save the items in a list

    support1 = items[1] # support 

    confidence1 = items[2][0][2]
    lift1 = items[2][0][3]

    results_1.append([item_data[0],item_data[1],round(support1,3),round(confidence1,3),round(lift1,2)])
print(results_1)

[['escalope', 'mushroom cream sauce', 0.006, 0.301, 3.79], ['pasta', 'escalope', 0.006, 0.373, 4.7], ['ground beef', 'herb & pepper', 0.016, 0.323, 3.29], ['tomato sauce', 'ground beef', 0.005, 0.377, 3.84], ['whole wheat pasta', 'olive oil', 0.008, 0.271, 4.12], ['shrimp', 'pasta', 0.005, 0.322, 4.51], ['shrimp', 'frozen vegetables', 0.005, 0.233, 3.25], ['ground beef', 'spaghetti', 0.005, 0.571, 3.28], ['nan', 'escalope', 0.006, 0.301, 3.79], ['nan', 'escalope', 0.006, 0.373, 4.7], ['frozen vegetables', 'spaghetti', 0.009, 0.311, 3.17], ['milk', 'frozen vegetables', 0.005, 0.203, 3.09], ['shrimp', 'frozen vegetables', 0.007, 0.305, 3.2], ['frozen vegetables', 'spaghetti', 0.006, 0.206, 3.12], ['shrimp', 'frozen vegetables', 0.006, 0.215, 3.01], ['frozen vegetables', 'spaghetti', 0.007, 0.239, 3.5], ['ground beef', 'spaghetti', 0.005, 0.323, 3.28], ['ground beef', 'herb & pepper', 0.007, 0.391, 3.98], ['nan', 'ground beef', 0.016, 0.323, 3.29], ['ground beef', 'spaghetti', 0.006, 0.393, 4.0], ['milk', 'ground beef', 0.005, 0.224, 3.4], ['tomato sauce', 'nan', 0.005, 0.377, 3.84], ['shrimp', 'ground beef', 0.006, 0.523, 3.01], ['milk', 'spaghetti', 0.007, 0.203, 3.08], ['soup', 'olive oil', 0.005, 0.225, 3.42], ['nan', 'whole wheat pasta', 0.008, 0.271, 4.13], ['shrimp', 'nan', 0.005, 0.322, 4.52], ['pancakes', 'spaghetti', 0.005, 0.201, 3.05], ['shrimp', 'nan', 0.005, 0.233, 3.26], ['nan', 'ground beef', 0.005, 0.571, 3.28], ['nan', 'frozen vegetables', 0.009, 0.311, 3.17], ['milk', 'frozen vegetables', 0.005, 0.203, 3.09], ['shrimp', 'nan', 0.007, 0.305, 3.2], ['nan', 'frozen vegetables', 0.006, 0.206, 3.13], ['shrimp', 'nan', 0.006, 0.215, 3.02], ['nan', 'frozen vegetables', 0.007, 0.239, 3.5], ['nan', 'ground beef', 0.005, 0.323, 3.28], ['nan', 'ground beef', 0.007, 0.391, 3.98], ['nan', 'ground beef', 0.006, 0.393, 4.0], ['milk', 'ground beef', 0.005, 0.224, 3.41], ['shrimp', 'nan', 0.006, 0.523, 3.01], ['milk', 'spaghetti', 0.007, 0.203, 3.09], ['soup', 'nan', 0.005, 0.225, 3.43], ['pancakes', 'nan', 0.005, 0.201, 3.06]]

:

In [ ]:
df_results2 = pd.DataFrame(results_1,columns=['Product1','Product2','Support','Confidence','Lift'])
df_results2.head()

NameError: name 'pd' is not defined