## Decision Tree Classifier model

### Business Statement: Build a predictive model that prescirbes the drug to patients based on their BP,Cholestrol and Sodium levels accuractely.

1) Data Gathering
2) Perform the basic data quality checks
3) Separate X and Y features. X:Independenet features and Y:Dependenet feature/Target feature
4) Splitting data into training and testing 
    training : 60%-90% 
    testing : 40%-10%
5) Feature Engg.. Data cleaning, Data preprocessing(scaling of data)
6) Model Buidling
7) Hyperparameter tuning
8) Model Evaluation
9) Save the model and preprocessor pipeline

### Step 1. Data Gathering

In [61]:
path = r"https://raw.githubusercontent.com/sindhura-nk/Datasets/refs/heads/main/drug200.csv"
import pandas as pd
df = pd.read_csv(path)
df.head()

   Age Sex      BP Cholesterol  Na_to_K   Drug
0   23   F    HIGH        HIGH   25.355  DrugY
1   47   M     LOW        HIGH   13.093  drugC
2   47   M     LOW        HIGH   10.114  drugC
3   28   F  NORMAL        HIGH    7.798  drugX
4   61   F     LOW        HIGH   18.043  DrugY

### Step2: Basic data quality checks

In [62]:
df.shape

(200, 6)

In [63]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Age          200 non-null    int64
 1   Sex          200 non-null    str
 2   BP           200 non-null    str
 3   Cholesterol  200 non-null    str
 4   Na_to_K      200 non-null    float64
 5   Drug         200 non-null    str
dtypes: float64(1), int64(1), str(4)
memory usage: 9.5 KB

In [64]:
# Check for duplicates
df.duplicated().sum()

np.int64(0)

In [65]:
df=df.drop_duplicates()

In [66]:
# Check for Missing data
df.isna().sum()

Age            0
Sex            0
BP             0
Cholesterol    0
Na_to_K        0
Drug           0
dtype: int64

## Step 3 : Separate X and Y features
    
    X : all features except Drug
    Y : Drug

In [67]:
X = df.drop(columns='Drug')
Y = df[['Drug']]

In [68]:
X.head()

   Age Sex      BP Cholesterol  Na_to_K
0   23   F    HIGH        HIGH   25.355
1   47   M     LOW        HIGH   13.093
2   47   M     LOW        HIGH   10.114
3   28   F  NORMAL        HIGH    7.798
4   61   F     LOW        HIGH   18.043

In [69]:
Y.head()

    Drug
0  DrugY
1  drugC
2  drugC
3  drugX
4  DrugY

## Step 4: Splitting the data into training and testing

    85%: training
    15%: testing

To check the performance of the model. Helps in overcoming overfitting and underfitting scenarios

In [70]:
df.shape

(200, 6)

In [71]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(X,Y,train_size=0.85,test_size=0.15,random_state=42)

In [72]:
print(f"Shape of training data: {xtrain.shape}")
print(f"Shape of testing data: {xtest.shape}")

Shape of training data: (170, 5)
Shape of testing data: (30, 5)

In [73]:
xtrain.head()

     Age Sex    BP Cholesterol  Na_to_K
9     43   M   LOW      NORMAL   19.368
18    23   M   LOW        HIGH    7.298
55    26   F   LOW        HIGH   14.160
75    26   M   LOW      NORMAL   20.909
150   49   M  HIGH      NORMAL    8.700

In [74]:
xtest.head()

     Age Sex      BP Cholesterol  Na_to_K
95    36   M     LOW      NORMAL   11.424
15    16   F    HIGH      NORMAL   15.516
30    18   F  NORMAL      NORMAL    8.750
158   59   F     LOW        HIGH   10.444
128   47   M     LOW      NORMAL   33.542

In [75]:
ytrain.head()

      Drug
9    DrugY
18   drugC
55   drugC
75   DrugY
150  drugA

In [76]:
ytest.head()

      Drug
95   drugX
15   DrugY
30   drugX
158  drugC
128  DrugY

## Step 5: Data Cleaning and Data Preprocessing

In [77]:
xtrain.info()

<class 'pandas.DataFrame'>
Index: 170 entries, 9 to 102
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Age          170 non-null    int64
 1   Sex          170 non-null    str
 2   BP           170 non-null    str
 3   Cholesterol  170 non-null    str
 4   Na_to_K      170 non-null    float64
dtypes: float64(1), int64(1), str(3)
memory usage: 8.0 KB

In [78]:
xtrain.select_dtypes(include='str').columns

Index(['Sex', 'BP', 'Cholesterol'], dtype='str')

In [79]:
list(xtrain.select_dtypes(include='str').columns)

['Sex', 'BP', 'Cholesterol']

In [80]:
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler,OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer

cat = list(xtrain.select_dtypes(include='str').columns)
con = list(xtrain.select_dtypes(include='number').columns)

con_pipe = make_pipeline(
    SimpleImputer(strategy='mean'),
    StandardScaler())

cat_pipe = make_pipeline(
    SimpleImputer(strategy='most_frequent'),
    OneHotEncoder(handle_unknown='ignore',sparse_output=False))

pre = ColumnTransformer([
    ("cat",cat_pipe,cat),
    ("con",con_pipe,con)
]).set_output(transform='pandas')

In [81]:
pre

ColumnTransformer(transformers=[('cat',
                                 Pipeline(steps=[('simpleimputer',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('onehotencoder',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False))]),
                                 ['Sex', 'BP', 'Cholesterol']),
                                ('con',
                                 Pipeline(steps=[('simpleimputer',
                                                  SimpleImputer()),
                                                 ('standardscaler',
                                                  StandardScaler())]),
                                 ['Age', 'Na_to_K'])])

In [82]:
pre.fit(xtrain)

ColumnTransformer(transformers=[('cat',
                                 Pipeline(steps=[('simpleimputer',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('onehotencoder',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False))]),
                                 ['Sex', 'BP', 'Cholesterol']),
                                ('con',
                                 Pipeline(steps=[('simpleimputer',
                                                  SimpleImputer()),
                                                 ('standardscaler',
                                                  StandardScaler())]),
                                 ['Age', 'Na_to_K'])])

In [83]:
xtrain_pre = pre.transform(xtrain)
xtest_pre = pre.transform(xtest)

In [84]:
xtrain_pre.head()

,cat__Sex_F,cat__Sex_M,cat__BP_HIGH,cat__BP_LOW,cat__BP_NORMAL,cat__Cholesterol_HIGH,cat__Cholesterol_NORMAL,con__Age,con__Na_to_K
9,0.0,1.0,0.0,1.0,0.0,0.0,1.0,-0.109364,0.449038
18,0.0,1.0,0.0,1.0,0.0,1.0,0.0,-1.340615,-1.233558
55,1.0,0.0,0.0,1.0,0.0,1.0,0.0,-1.155927,-0.276974
75,0.0,1.0,0.0,1.0,0.0,0.0,1.0,-1.155927,0.663858
150,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.260011,-1.038115

In [85]:
xtest_pre.head()

,cat__Sex_F,cat__Sex_M,cat__BP_HIGH,cat__BP_LOW,cat__BP_NORMAL,cat__Cholesterol_HIGH,cat__Cholesterol_NORMAL,con__Age,con__Na_to_K
95,0.0,1.0,0.0,1.0,0.0,0.0,1.0,-0.540302,-0.658381
15,1.0,0.0,1.0,0.0,0.0,0.0,1.0,-1.771553,-0.087943
30,1.0,0.0,0.0,0.0,1.0,0.0,1.0,-1.648428,-1.031145
158,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.875637,-0.794996
128,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.136886,2.424939